---
# tasks file for redis

- include_vars: ../vars/main.yml

- name: Install rsyslog latest
  dnf:
    name: rsyslog
    state: latest
  become: true
  become_method: sudo
  when:  ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: Copy file rsyslog.conf with owner and permissions
  ansible.builtin.copy:
    src: ../files/rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: Copy file legacy_files.conf with owner and permissions
  ansible.builtin.copy:
    src: ../files/legacy_files.conf
    dest: /etc/rsyslog.d/legacy_files.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: Copy file http-ssl-access.conf with owner and permissions
  ansible.builtin.copy:
    src: ../files/http-ssl-access.conf
    dest: /etc/rsyslog.d/http-ssl-access.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: Copy file http-ssl-request.conf with owner and permissions
  ansible.builtin.copy:
    src: ../files/http-ssl-request.conf
    dest: /etc/rsyslog.d/http-ssl-request.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: Copy file http-ssl-error.conf with owner and permissions
  ansible.builtin.copy:
    src: ../files/http-ssl-error.conf
    dest: /etc/rsyslog.d/http-ssl-error.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: Copy file http-access.conf with owner and permissions
  ansible.builtin.copy:
    src: ../files/http-access.conf
    dest: /etc/rsyslog.d/http-access.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: Copy file http-error.conf with owner and permissions
  ansible.builtin.copy:
    src: ../files/http-error.conf
    dest: /etc/rsyslog.d/http-error.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'

- name: apply template file with owner and permissions
  template: 
    src: ../files/racdata.j2
    dest: /etc/rsyslog.d/racdata.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  become_method: sudo
  when: ansible_distribution_major_version == '8' and ansible_distribution|string =='Red Hat Entreprise'
  notify:
    - Restart rsyslog
